In [2]:
import numpy as np

In [3]:
M = 10
m = np.zeros((M,M))

In [4]:
#m1 = np.ones_like(m)

In [5]:
#np.full_like(m, 5)

In [6]:
m = np.random.randint(0, 2, (M,M))

In [7]:
#for i in range(10):
#    for j in range(10):
#        print(i,j)

In [8]:
m

array([[1, 0, 1, 1, 1, 0, 1, 0, 0, 0],
       [1, 0, 1, 0, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 0, 1, 1, 1, 1, 0],
       [0, 1, 1, 0, 1, 1, 1, 1, 1, 0],
       [1, 0, 0, 1, 1, 0, 0, 1, 1, 1],
       [0, 1, 1, 1, 1, 1, 1, 1, 0, 0],
       [0, 1, 0, 1, 0, 0, 0, 1, 1, 1],
       [1, 1, 0, 0, 0, 1, 1, 0, 0, 0],
       [1, 0, 0, 0, 1, 1, 0, 0, 1, 0]])

In [22]:
M = 10
m = np.random.randint(0,2,(M,M))
ma = m.copy()


for i in range(M):
    for j in range(M):
        if i == 0:
            if j == 0:
                n = m[i+1, j] + m[i+1, j+1] + m[i, j+1]
            elif j == M-1:
                n = m[i, j-1] + m[i+1, j-1] + m[i+1, j]
            else:
                n = m[i+1, j] + m[i+1, j+1] + m[i, j+1] + m[i, j-1] + m[i+1, j-1]
                
        elif i == M-1:
            if j == 0:
                n = m[i-1, j] + m[i-1, j+1] + m[i, j+1]
            elif j == M-1:
                n = m[i-1, j] + m[i-1, j-1] + m[i, j-1]
            else:
                n = m[i-1, j] + m[i-1, j+1] + m[i, j+1] + m[i-1, j-1] + m[i, j-1]
                
        elif j == 0:
            n = m[i-1,j] + m[i-1, j+1] + m[i, j+1] + m[i+1, j+1] + m[i+1, j]
        
        elif j == M-1:
            n = m[i-1,j] + m[i-1, j-1] + m[i, j-1] + m[i+1, j-1] + m[i+1, j]
            
        else:
            n = m[i-1,j] + m[i-1, j-1] + m[i, j-1] + m[i+1, j-1] + m[i+1, j] + m[i+1, j+1] + m[i, j+1] + m[i-1, j-1]
        
    
        if m[i,j] == 0:
            if n == 3:
                ma[i,j] = 1
        else:
            if not (n == 2 or n == 3):
                ma[i,j] = 0
            
print(ma)

[[0 1 1 1 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 1]
 [1 0 0 0 0 0 0 1 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [0 1 0 0 0 1 0 0 1 0]
 [0 1 1 0 1 0 0 0 0 1]
 [0 0 0 1 1 1 0 1 1 1]
 [0 1 0 0 1 0 0 0 0 1]
 [0 0 0 1 1 1 0 0 1 1]
 [0 0 0 1 1 1 1 0 1 0]]


In [23]:
m

array([[1, 1, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 1, 0, 0, 1, 1],
       [1, 1, 1, 1, 1, 1, 0, 1, 1, 1],
       [0, 1, 1, 0, 0, 1, 1, 1, 0, 0],
       [0, 0, 1, 0, 0, 1, 1, 0, 1, 0],
       [1, 0, 0, 1, 0, 0, 1, 0, 0, 1],
       [1, 0, 1, 0, 1, 1, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 1, 0, 1, 1, 0, 1, 1, 0],
       [0, 0, 0, 1, 0, 0, 1, 1, 1, 0]])

In [24]:
ma

array([[0, 1, 1, 1, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 1, 0, 0, 1, 0],
       [0, 1, 1, 0, 1, 0, 0, 0, 0, 1],
       [0, 0, 0, 1, 1, 1, 0, 1, 1, 1],
       [0, 1, 0, 0, 1, 0, 0, 0, 0, 1],
       [0, 0, 0, 1, 1, 1, 0, 0, 1, 1],
       [0, 0, 0, 1, 1, 1, 1, 0, 1, 0]])

In [33]:
def life_step (x):
    print(x)

In [34]:
life_step(ma)

[[0 1 1 1 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 1]
 [1 0 0 0 0 0 0 1 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [0 1 0 0 0 1 0 0 1 0]
 [0 1 1 0 1 0 0 0 0 1]
 [0 0 0 1 1 1 0 1 1 1]
 [0 1 0 0 1 0 0 0 0 1]
 [0 0 0 1 1 1 0 0 1 1]
 [0 0 0 1 1 1 1 0 1 0]]
